### ISSUE TITLE
fix order-dependent spec

### ISSUE THREAD

**Issue by MothOnMars** [GSA/i14y#45]
**Steps:**
Run the spec suite with the `35490` seed:
`rspec spec/ --seed 35490`

**Expected Results:**
- all specs pass

**Actual Results:**
- One spec fails:
```
Failures:

  1) API::V1::Documents POST /api/v1/documents success case stores the appropriate fields in the Elasticsearch document
     Failure/Error: expect(document.path).to eq("http://www.gov.gov/goo.html")

       expected: "http://www.gov.gov/goo.html"
            got: "http://www.gov.gov/url4.html"

       (compared using ==)
     # ./spec/requests/api/v1/documents_spec.rb:62:in `block (4 levels) in <top (required)>'
```
